# Generated by Django 3.2.8 on 2021-10-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('vedio', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
